---
title: "NAFLD Study Data Anaylsis"
author: "Benedikt Hild and Matthew Dreier"
date: "9/17/2018"
output: html_document
---

***

##Data Setup

```{r setup, eval = TRUE, include = TRUE, message = FALSE, warning = FALSE}

#load packages
library(ggplot2)

##function to change names of columns
changeColName <- function(df, oldName, newName) {
  
  #if the oldName is not in the data frame, return the unmutated data frame
  if (oldName %in% names(df) == FALSE) {
    return(df)
  }
  
  #change name and return mutated data frame
  names(df)[names(df) == oldName] <- newName
  return(df)
}

#read data
cd <- read.csv("AllExp.csv")

#change column names and delete uneeded columns
cd <- changeColName(cd, "Food", "Diet")
cd <- changeColName(cd, "Gender", "Sex")
cd$X <- NULL
cd$X.1 <- NULL

#change date to standard format
cd$Date <- as.Date(cd$Date, "%m/%d/%y")

##Calculate days after start
  #initiialize days variable
cd$Days <- NA

#for each sex
for (sex in unique(cd$Sex)){

  #for each experiment
  for (experiment in unique(cd$Experiment[cd$Sex == sex])) {
  
    #for each microbiome
    for (microbiome in unique(cd$Microbiome)) {
    
    #find the lowest date for the given sex/experiment/microbiome combination
    lowdate <- min(cd$Date[cd$Experiment == experiment & cd$Microbiome == microbiome & cd$Sex == sex])
  
    #set days 
    cd$Days[cd$Experiment == experiment & cd$Microbiome == microbiome & cd$Sex == sex] <- cd$Date[cd$Experiment == experiment & cd$Microbiome == microbiome & cd$Sex == sex] - lowdate
    }
  }
}


##Create unique identifier for each mouse
  #initialize UID variable
cd$UID <- NA

#create column that uniquely identifies each mouse
cd$Temp <- paste(cd$Experiment, cd$Microbiome, cd$Diet, cd$Cage, cd$Mouse, cd$Sex)

#for each mouse
for (mouse in unique(cd$Temp)) {
  mouse.list <- as.vector(strsplit(mouse, " ")[[1]])
 
  #convert microbiome to a number, 1 = Wildling 2 = Lab
  microbiome <- "2"
  if (mouse.list[2] == "Wild") {
    microbiome <- "1"
        }
 
  #convert diet to anumber, 1 = High Fat 2 = Chow
  diet <- "2"
  if (mouse.list[3] == "Fat") {
    diet <- "1"
  }
  
  #change sex to a number, 1 = Female 2 = Male
  sex <- "2"
  if (mouse.list[6] == "Female") {
    sex <- "1"
  }
 
  #create UID, a 6 digit number with format [gender][experiment][microbiome][diet][cage][mouse]
  uid <- paste0(sex, mouse.list[1], microbiome, diet, mouse.list[4], mouse.list[5])
  cd$UID[cd$Temp == mouse] <- as.numeric(uid)
}

#remove temp variable
cd$Temp <- NULL

##Create function to remove outliers
  #df: The data frame containing var
  #var: The variable from which to remove outliers
  #tol: The maximum change in var as a proportion
removeOutliers <- function(df, var, tol) {
  
  #create new variable to hold model
  df$Trend <- NA
  
  #for each mouse
  for (mouse in unique(df$UID)) {
    
    #create linear model of variable by days
    model <- lm(df[,var][df$UID == mouse]~df$Days[df$UID == mouse])
    
    #populate trend variable with model
    df$Trend[df$UID == mouse] <- model[[1]][2] * df$Days[df$UID == mouse] + model[[1]][1]
    
  }
  
  #remove rows where var differs from model by more than tol
  df[,var][abs((df[,var] - df$Trend) / df$Trend) > tol] <- NA
  
  #remove trend variable and return df
  df$Trend <- NULL
  return(df)
  
}

##Create new variable for condition (combination of microbiome and food)
cd$Condition <- paste(cd$Microbiome, cd$Diet)
cols <- c("darkturquoise","goldenrod1", "blue3", "darkolivegreen4")

```


##Analysis of Weight

```{r weight, eval = TRUE, include = TRUE, message = FALSE, warning = FALSE}

##Find proportional weight 
  #intialize proportional weight variable
cd$PercWeight <- NA

#for each mouse
for (mouse in unique(cd$UID)) {
 
  #find minimum day (start day) and minimum weight (on start day)
  minDay <- min(cd$Day[cd$UID == mouse])
  minWeight <- cd$Weight[cd$UID == mouse & cd$Day == minDay]
 
  #find proportional weight for the current mouse
  cd$PercWeight[cd$UID == mouse] <- cd$Weight[cd$UID == mouse] / minWeight
}

#convert proportional weight to a percentage
cd$PercWeight <- cd$PercWeight * 100

##Plot weight
cdFemale <- subset(cd, cd$Sex == "Female")

#create graph
pWeightFemale <- ggplot(cdFemale, aes(x = cdFemale$Days, y = cdFemale$Weight, color = cdFemale$Condition)) +
  geom_smooth() +
  labs(x = "Day", y = "Weight (g)", title = "Absolute Weight of Female Mice") +
  scale_colour_manual("", values = cols, breaks = c("Lab Chow", "Lab Fat", "Wild Chow", "Wild Fat")) +
  theme_set(theme_bw(base_size = 20)) +
  theme(plot.title = element_text(hjust = 0.5))

  pWeightFemale

##Plot proportional weight

#create graph
pPercWeightFemale <- ggplot(cdFemale, aes(x = cdFemale$Days, y = cdFemale$PercWeight, color = cdFemale$Condition)) +
  geom_smooth() +
  labs(x = "Day", y = "Proportional Weight (%)", title = "Proportional Weight of Female Mice") +
  scale_colour_manual("", values = cols, breaks = c("Lab Chow", "Lab Fat", "Wild Chow", "Wild Fat")) +
  theme(plot.title = element_text(hjust = 0.5))
  
  pPercWeightFemale
  
##Bin weights
  #create new variable for weight gain and set it to high when percent weight exceeds 150
cd$WeightGain <- "low"
cd$WeightGain[cd$PercWeight > 150] <- "high"


##Find day mouse crosses weight threshold
weightThreshConds <- c()
weightThreshDays <- c()
  
#for each condition
for (condition in unique(cd$Condition)) {
  
  #for each mouse in that condition
  for (mouse in unique(cd$UID[cd$Condition == condition])) {
    
    #if that mouse crosses weight threshold
    if (length(unique(cd$WeightGain[cd$Condition == condition & cd$UID == mouse])) == 2) {
      
      #update lists
      weightThreshConds <- c(weightThreshConds, condition)
      weightThreshDays <- c(weightThreshDays, min(cd$Days[cd$UID == mouse & cd$Condition == condition & cd$WeightGain == "high"]))
    }
  }
}

##plot day mice cross weight threshold
ggplot() +
  geom_violin(aes(x = weightThreshConds, y = weightThreshDays, fill = weightThreshConds)) +
  geom_boxplot(aes(x = weightThreshConds, y = weightThreshDays, fill = weightThreshConds), color = "black", width = 0.2) +
  geom_jitter(aes(x = weightThreshConds, y = weightThreshDays), color = "white", fill = "black", pch = 21) +
  scale_fill_manual(values = cols[c(1,2,4)], breaks = c("Lab Chow", "Lab Fat", "Wild Fat")) +
  labs(x = NULL, y = "# Days to 150% Weight") +
  theme(legend.position = "none")

#for each mouse
for (mouse in unique(cd$UID)) {
  
  #if the mouse ever has "high" weight gain, weight gain variable to "high" in all rows
  if ("high" %in% unique(cd$WeightGain[cd$UID == mouse])) {
    cd$WeightGain[cd$UID == mouse] <- "high"
  }
}

##Create table with weight gain category by condition
prop.table(table(cd$WeightGain[cd$Days == 0], cd$Condition[cd$Days == 0]), margin = 2)

#plot weight gain bins
barplot(prop.table(table(cd$WeightGain[cd$Days == 0], cd$Condition[cd$Days == 0]), margin = 2), col = c("black", "light gray"), main = "Weight Gain of Female Mice", ylab = "Proportion")
legend("bottomright", inset = 0.02, legend = c(">50% Gain", "<50% Gain"), fill = c("black", "light gray"))

# sub <- subset(cdFemale, cdFemale$Condition == "Wild Fat")
# 
# pBinWeight <- ggplot(sub, aes(x = sub$Days, y = sub$PercWeight, color = sub$WeightGain)) +
#   geom_smooth() +
#   labs(x = "Day", y = "Proportional Weight (%)", title = "Wildling High Fat Mice") +
#   xlim(limits = c(0, maxDaysFemale)) +
#   ylim(limits = c(minPercWeightFemale, maxPercWeightFemale)) +
#   scale_colour_manual("", values = cols, breaks = c("high", "low"), labels = c(">50% Gain", "<50% Gain")) +
#   theme(plot.title = element_text(hjust = 0.5))
# 
# 
# pBinTemp <- ggplot(sub, aes(x = sub$Days, y = sub$Temperature, color = sub$WeightGain)) +
#   geom_smooth() +
#   geom_point() + 
#   labs(x = "Day", y = "Temperature (°C)", title = "Wildling High Fat Mice") +
#   scale_colour_manual("", values = cols, breaks = c("high", "low"), labels = c(">50% Gain", "<50% Gain")) +
#   theme(plot.title = element_text(hjust = 0.5))
# 
# pBinGlucose <- ggplot(sub, aes(x = sub$Days, y = sub$Glucose, color = sub$WeightGain)) +
#   geom_smooth() +
#   labs(x = "Day", y = "Blood Glucose (mg/dL)", title = "Wildling High Fat Mice") +
#   xlim(limits = c(0, maxDaysFemale)) +
#   scale_colour_manual("", values = cols, breaks = c("high", "low"), labels = c(">50% Gain", "<50% Gain")) +
#   theme(plot.title = element_text(hjust = 0.5))

```


```{r, eval = FALSE, include = FALSE}
#create a new variable for proportional glucose
cd$PropGlucose <- NA
 
#loop through each mouse with UID
for (mouse in unique(cd$UID)) {
 
  #find minimum day (start day) and minimum weight (on start day)
  minDay <- min(cd$Day[cd$UID == mouse])
  minGlucose <- cd$Glucose[cd$UID == mouse & cd$Day == minDay]
 
  #find and save proportional weight for the current mouse
  cd$PropGlucose[cd$UID == mouse] <- cd$Glucose[cd$UID == mouse] / minGlucose
 
}

#create a new variable for proportional glucose
cd$PropTemp <- NA
 
#loop through each mouse with UID
for (mouse in unique(cd$UID)) {
 
  #find minimum day (start day) and minimum weight (on start day)
  minTemp <- logical(0)
  minDay <- 0
  while (length(minTemp) == 0) {
    minDay <- minDay + 1
    minTemp <- cd$Temperature[cd$UID == mouse & cd$Day == minDay]
  }

 
  #find and save proportional weight for the current mouse
  cd$PropTemp[cd$UID == mouse] <- cd$Temperature[cd$UID == mouse] / minTemp
 
}

#Plot proportional glucose gain of all mice

cd$Color <- paste(cd$Microbiome, cd$Food)

cdFemale <- subset(cd, cd$Gender == "Female")

plotPropGlucoseFemale <- ggplot(cdFemale, aes(x = cdFemale$Days, y = cdFemale$PropGlucose, color = cdFemale$Color)) +
                                 geom_smooth() +
  scale_x_continuous(breaks=seq(0,maxdays, 7), limits = c(mindays, maxdays)) +
 # xlim(c(mindays, maxdays)) +
  xlab("Days") +
  ylab("Glucose [mg/dl]") +
  scale_colour_manual("", values = c("darkturquoise","goldenrod1", "blue3", "darkolivegreen4"), breaks = c("Lab Chow", "Lab Fat", "Wild Chow", "Wild Fat")) +
  theme_set(theme_bw(base_size = 20) ) +
    theme(plot.title = element_text(hjust = 0.5)) +
      ggtitle("Glucoese over Time")

  

#Plot proportional TEMPERATURE gain of all mice

cd$Color <- paste(cd$Microbiome, cd$Food)

cdFemale <- subset(cd, cd$Gender == "Female")

plotPropTemperatureFemale <- ggplot(cdFemale, aes(x = cdFemale$Days, y = cdFemale$PropTemp, color = cdFemale$Color)) +
                                 geom_smooth() +
  scale_x_continuous(breaks=seq(0,maxdays, 7), limits = c(mindays, maxdays)) +
 # xlim(c(mindays, maxdays)) +
  xlab("Days") +
  ylab("Temperature[C]") +
  scale_colour_manual("", values = c("darkturquoise","goldenrod1", "blue3", "darkolivegreen4"), breaks = c("Lab Chow", "Lab Fat", "Wild Chow", "Wild Fat")) +
  theme_set(theme_bw(base_size = 20) ) +
    theme(plot.title = element_text(hjust = 0.5)) +
      ggtitle("Temperature over Time")

print(plotPercWeightFemale)
  
print(plotPropGlucoseFemale)  
print(plotPropTemperatureFemale)  

cd$WeightBin <- FALSE

cd$WeightBin[cd$PercWeight > 1.25] <- TRUE

FatWildHigh <- subset(cd, cd$WeightBin == TRUE & cd$Microbiome == "Wild" & cd$Food == "Fat" & cd$Days == "31")

cd$WeightBin[cd$PercWeight < 1.25] <- TRUE

FatWildLow <- subset(cd, cd$WeightBin == TRUE & cd$Microbiome == "Wild" & cd$Food == "Fat" & cd$Days == "31")

for (microbiome in unique(cd$Microbiome)){
  
  for(food in unique(cd$Food)){
    
    temp <- subset(cd, cd$Weight[cd$Microbiome == "Wild" & cd$Food == "Fat"])
    
    HistoWeight <- ggplot(data = temp, aes(temp$Weight)) +
      geom_histogram()

print(HistoWeight)
  }
}

HistoWeight <- ggplot(data = cd, aes(cd$Weight)) +
  geom_histogram()

print(HistoWeight)

for (histo in unique(cd$Days)){
  
  day <- subset(cd, cd$Days > "30")
  
  histogrammweight <- ggplot(data = cd, aes(y = cd$Weight))+
    geom_histogram()
  
  
}


print(histogrammweight)


for (sex in unique(cd$Gender)) {
  for (microbiome in unique(cd$Microbiome)) {
    for (food in unique(cd$Food)) {
      
      sub <- subset(cd, cd$Gender == sex & cd$Microbiome == microbiome & cd$Food == food)
      
      model <- lm(sub$Weight~sub$Temperature)
      
      p <- ggplot(data = sub, aes(x = sub$Temperature, y = sub$Weight, color = sub$Days)) + geom_point() + geom_abline(aes(intercept = as.numeric(model[[1]][1]), slope = as.numeric(model[[1]][2]))) + labs(x = "Temperature", y = "Weight", title = paste(sex, microbiome, food), subtitle = paste("Pearson Correlation: ", as.numeric(cor.test(sub$Temperature, sub$Weight)[4]), ", p = ", as.numeric(cor.test(sub$Temperature, sub$Weight)[3])))
      
      print(p)
      
      p2 <- ggplot(data = sub, aes(x = sub$UID, y = sub$Weight, color = sub$Days)) + geom_point()
      
      print(unique(sub$UID))
      
      print(p2)
      
    }
  }
}

harvestData <- read.csv("Harvest Data.csv")

harvestData <- subset(harvestData, is.na(harvestData$Mouse.Weight..g.) == FALSE)

harvestSub <- subset(harvestData, harvestData$Microbiome == "Wildling")

pHarvest <- ggplot(harvestSub, aes(x = harvestSub$Mouse.Weight..g., y = harvestSub$Liver.Weight..g., color = harvestSub$Diet)) +
  geom_point() +
  geom_smooth(method = lm) +
  labs(x = "Mouse Weight (g)", y = "Liver Weight (g)") +
  scale_colour_manual("", values = cols, breaks = c("Fat", "Chow")) +
  theme_set(theme_bw(base_size = 20)) +
  theme(plot.title = element_text(hjust = 0.5))

harvestSub2 <- subset(harvestData, harvestData$Microbiome == "Lab")

pHarvest2 <- ggplot(harvestSub2, aes(x = harvestSub2$Mouse.Weight..g., y = harvestSub2$Liver.Weight..g., color = harvestSub2$Diet)) +
  geom_point() +
  geom_smooth(method = lm) +
  labs(x = "Mouse Weight (g)", y = "Liver Weight (g)") +
  scale_colour_manual("", values = cols, breaks = c("Fat", "Chow")) +
  theme_set(theme_bw(base_size = 20)) +
  theme(plot.title = element_text(hjust = 0.5))

cor.test(harvestSub$Mouse.Weight..g.[harvestSub$Diet == "Chow"], harvestSub$Liver.Weight..g.[harvestSub$Diet == "Chow"])

cor.test(harvestSub$Mouse.Weight..g.[harvestSub$Diet == "Fat"], harvestSub$Liver.Weight..g.[harvestSub$Diet == "Fat"])

cor.test(harvestSub2$Mouse.Weight..g.[harvestSub2$Diet == "Chow"], harvestSub2$Liver.Weight..g.[harvestSub2$Diet == "Chow"])

cor.test(harvestSub2$Mouse.Weight..g.[harvestSub2$Diet == "Fat"], harvestSub2$Liver.Weight..g.[harvestSub2$Diet == "Fat"])

```

